import React from 'react';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import './App.css';
import { Desktop } from "./Desktop";
import './NavigationToolbar.css'; // Import the CSS file

// database imports
import { signUp } from './authService';
import { db } from './firebase';
import { doc, setDoc } from 'firebase/firestore';


// About Page Component
const AboutPage = () => {
  return (
    <div className="page-container">
      <h1>About MindQuill</h1>
      <p>MindQuill is an interactive learning platform geared toward individuals with dyslexia.</p>
      <p>By utilizing the OpenDyslexia font and a dyslexia-friendly color scheme, anyone can easily and accessibly interact with an AI study assistant.</p>
      <p>Upload PDF documents and get instant summaries or short comprehension quizzes generated by the Google Gemini API.</p>
      <p>Create an account to track your progress and get personalized stats!</p>
    </div>
  );
};

// Progress Page Component
const ProgressPage = () => {
  return (
    <div className="page-container">
      <h1>Your Learning Progress</h1>
      <div className="progress-stats">
        <div className="stat-card">
          <h3>Documents Processed</h3>
          <p className="stat-number">xx</p>
        </div>
        <div className="stat-card">
          <h3>Quiz Accuracy</h3>
          <p className="stat-number">xx%</p>
        </div>
        <div className="stat-card">
          <h3>Hours Saved</h3>
          <p className="stat-number">x.x</p>
        </div>
      </div>
      <div className="recent-activity">
        <h2>Recent Activity</h2>
        <ul>
          <li>Completed quiz on "foo" - xx% accuracy</li>
          <li>Summarized "foo" - x.x pages</li>
          <li>Started learning "foo"</li>
        </ul>
      </div>
    </div>
  );
};

const SignUpPage = () => {
  const [formData, setFormData] = React.useState({
    fullName: '',
    email: '',
    password: '',
    confirmPassword: ''
  });
  
  const [error, setError] = React.useState('');

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prevData => ({
      ...prevData,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    // Validate passwords match
    if (formData.password !== formData.confirmPassword) {
      setError('Passwords do not match');
      return;
    }
    
    try {
      // Sign up the user
      const userCredential = await signUp(formData.email, formData.password);
      const user = userCredential.user;
      
      // Create a user document in Firestore
      await setDoc(doc(db, "users", user.uid), {
        name: formData.fullName,
        email: formData.email,
        documents_processed: 0,
        "hours saved": 0,
        // Add any other initial user data fields
      });
      
      alert('Account created successfully!');
      // Redirect to home or dashboard
    } catch (error) {
      console.error('Error during signup:', error);
      setError(error.message);
    }
  };

  return (
    <div className="page-container">
      <h1>Create Your Account</h1>
      {error && <div className="error-message">{error}</div>}
      <form className="signup-form" onSubmit={handleSubmit}>
        <div className="form-group">
          <label htmlFor="fullName">Full Name</label>
          <input
            type="text"
            id="fullName"
            name="fullName"
            value={formData.fullName}
            onChange={handleChange}
            required
          />
        </div>
        
        <div className="form-group">
          <label htmlFor="email">Email Address</label>
          <input
            type="email"
            id="email"
            name="email"
            value={formData.email}
            onChange={handleChange}
            required
          />
        </div>
        
        <div className="form-group">
          <label htmlFor="password">Password</label>
          <input
            type="password"
            id="password"
            name="password"
            value={formData.password}
            onChange={handleChange}
            required
            minLength="8"
          />
        </div>
        
        <div className="form-group">
          <label htmlFor="confirmPassword">Confirm Password</label>
          <input
            type="password"
            id="confirmPassword"
            name="confirmPassword"
            value={formData.confirmPassword}
            onChange={handleChange}
            required
          />
        </div>
        
        <button type="submit" className="signup-button">Create Account</button>
      </form>
    </div>
  );
};

// Team Footer Component
// Team Footer Component (Compact Version)
// Team Footer Component (No Avatars)
const TeamFooter = () => {
  return (
    <footer className="team-footer">
      <div className="team-container">
        <h2 className="team-title">Our Team:</h2>
        <div className="team-members">
          <div className="team-member">
            <h3 className="member-name">Beckett Hayes</h3>
            <a href="https://www.linkedin.com/in/beckett-hayes-3a162a25b/" target="_blank" rel="noopener noreferrer" className="linkedin-button">
              LinkedIn
            </a>
          </div>
          
          <div className="team-member">
            <h3 className="member-name">Omkar Kulkarni</h3>
            <a href="https://www.linkedin.com/in/omkar-kulkarni-b7b742276/" target="_blank" rel="noopener noreferrer" className="linkedin-button">
              LinkedIn
            </a>
          </div>
          
          <div className="team-member">
            <h3 className="member-name">Kevin Angeles</h3>
            <a href="https://www.linkedin.com/in/angelesmkevin/" target="_blank" rel="noopener noreferrer" className="linkedin-button">
              LinkedIn
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
};

function App() {
  return (
    <BrowserRouter>
      <div className="App">
        <nav className="navigation-toolbar">
          <div className="logo-container">
            <Link to="/" className="logo-link">MindQuill</Link>
          </div>
          <div className="nav-links">
            <Link to="/" className="nav-link">Home</Link>
            <Link to="/about" className="nav-link">About</Link>
            <Link to="/progress" className="nav-link">Progress</Link>
            <Link to="/signup" className="nav-link">Sign Up</Link>
          </div>
        </nav>

        <div className="content-area">
          <Routes>
            <Route path="/" element={<Desktop />} />
            <Route path="/about" element={<AboutPage />} />
            <Route path="/progress" element={<ProgressPage />} />
            <Route path="/signup" element={<SignUpPage />} />
          </Routes>
        </div>
        
        {/* Add the Team Footer component here */}
        <TeamFooter />
      </div>
    </BrowserRouter>
  );
}

export default App;